#pragma config(Sensor, in2,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in7,    scoopPot,       sensorPotentiometer)
#pragma config(Sensor, dgtl8,  upperLimit,     sensorTouch)
#pragma config(Sensor, dgtl10, lowerLimit,     sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           seedDoorServo, tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           scoopMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int adjustThrottle(int input) {
	int output = 0;
	bool isPositive = false;
	if (input > -0.05 * 127 && input < 0.05 * 127)
		return 0;
	if (input > 0)
		isPositive = true;
	if (output > .85 * 127 || output < -.85 * 127)
		return isPositive ? 127 : -127;
	float percentThrottle = input / 127.0;
	output = isPositive ? 127 * percentThrottle * percentThrottle : -127 * (percentThrottle * percentThrottle);

	return output;
}

task main{
	bool closeServo = true;
	while (true) {
		motor[port2] = adjustThrottle(vexRT[Ch2]);
		motor[port3] = adjustThrottle(vexRT[Ch3]);

		if (vexRT[Btn5D] == 1)
			motor[port8] = 127;
		else if (vexRT[Btn6D] == 1)
			motor[port8] = -127;
		if (vexRT[Btn5D] == 0 && vexRT[Btn6D] == 0)
			motor[port8] = 0;

		if (vexRT[Btn5U] == 1 && !SensorBoolean[dgtl8])
			motor[port9] = 127;
		else if (vexRT[Btn6U] == 1 && !SensorBoolean[dgtl10])
			motor[port9] = -127;
		if (vexRT[Btn5U] == 0 && vexRT[Btn6U] == 0)
			motor[port9] = 0;

		if (vexRT[Btn8U] == 1)
			closeServo = false;
		if (vexRT[Btn8D] == 1)
			closeServo = true;
		if (closeServo == true)
			motor[port6] = 0;
		else
			motor[port6] = 127;
	} //wend








}
