#pragma config(Sensor, in2,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in7,    scoopPot,       sensorPotentiometer)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           seedDoorServo, tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           scoopMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main{

	int Ch1 = 1;
	int Ch2 = 2;
	int Ch3 = 3;
	int Ch4 = 4;
	while (true) {
		motor[port2] = vexRT[Ch2];
		motor[port3] = vexRT[Ch3];

	} //wend

}
