#pragma config(Sensor, in2,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in7,    scoopPot,       sensorPotentiometer)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           seedDoorServo, tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           scoopMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int adjustThrottle(int input) {
	int output = 0;
	bool isPositive = false;
	if (input > -0.05 * 127 && input < 0.05 * 127)
		return 0;
	if (input > 0)
		isPositive = true;
	if (output > .85 * 127 || output < -.85 * 127)
		return isPositive ? 127 : -127;
	float percentThrottle = input / 127.0;
	output = isPositive ? 127 * percentThrottle * percentThrottle : -127 * (percentThrottle * percentThrottle);

	return output;
}

task main{

	int Ch1 = 1;
	int Ch2 = 2;
	int Ch3 = 3;
	int Ch4 = 4;
	while (true) {
		motor[port2] = adjustThrottle(vexRT[Ch1]);
		motor[port3] = adjustThrottle(vexRT[Ch2]);

	} //wend
}
